version: '3'
services:
  frontend:
    # Use the production Dockerfile for the frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Expose the React app's port
    ports:
      - "3000:8000"
    # Set environment variables for React (if needed)
    environment:
      - NODE_ENV=production

  backend:
    # Use the production Dockerfile for the backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Expose the Django app's port
    ports:
      - "8000:8000"
    # Set environment variables for Django (replace with actual values)
    environment:
      - DJANGO_SECRET_KEY=your_secret_key
      - DJANGO_DEBUG=False
